# *****************************************************************************************
# *
# *        =============================================
# *                  LB Theme (eYRC 2024-25)
# *        =============================================
# *
# *
# *  Filename:        ekf.yaml
# *  Description:     Use this file to configure extended kalman filter parameters for robot localisation.
# *  Created:         31/12/2024
# *  Last Modified:   27/02/2025
# *  Modified by:     Updated to fix IMU drift
# *  Author:          e-Yantra Team
# *  
# *****************************************************************************************

### ekf config file ###
ekf_filter_node:
    ros__parameters:

        use_sim_time: false
        frequency: 30.0
        sensor_timeout: 0.1 
        two_d_mode: true

        # Transform configuration
        transform_time_offset: 0.0
        transform_timeout: 0.0
        print_diagnostics: true
        debug: false
        debug_out_file: /robot_localization/debug/file.txt
        publish_tf: true
        publish_acceleration: false
        reset_on_time_jump: true

        # Coordinate frames
        map_frame: map                   # Defaults to "map" if unspecified
        odom_frame: odom                 # Defaults to "odom" if unspecified
        base_link_frame: ebot_base_link  # Defaults to "base_link" if unspecified
        world_frame: odom                # Defaults to the value of odom_frame if unspecified

        # Odometry input configuration (wheel encoders)
        odom0: /odom

        # Odometry config - Use for position and linear velocity
        odom0_config: [true,  true,  false,  # x, y, z position
                       false, false, false,   # roll, pitch, yaw orientation (let IMU handle this)
                       true,  true,  false,   # x, y, z velocity
                       false, false, false,   # roll, pitch, yaw velocity (let IMU handle this)
                       false, false, false]   # x, y, z acceleration

        # Odometry queue and processing settings
        odom0_queue_size: 5  # Increased from 2 for better data fusion
        odom0_nodelay: false
        odom0_differential: false
        odom0_relative: false
        odom0_pose_rejection_threshold: 5.0  # Keep this relaxed for odometry
        odom0_twist_rejection_threshold: 1.0  # More strict than before for velocity outliers

        # IMU input configuration
        imu0: /sensors/imu1
        
        # IMU config - Use primarily for orientation and angular velocity
        imu0_config: [false, false, false,  # x, y, z position
                      false, false, true,   # roll, pitch (disabled), yaw (enabled)
                      false, false, false,  # x, y, z velocity
                      false, false, true,   # roll, pitch (disabled), yaw velocity (enabled)
                      true,  true,  false]  # x, y acceleration (enabled), z acceleration (disabled)

        # IMU processing settings
        imu0_nodelay: false
        imu0_differential: false
        imu0_relative: true  # Keep this true to handle initial bias
        imu0_queue_size: 10  # Increased from 7 for smoother fusion
        
        # Stricter rejection thresholds to handle drift
        imu0_pose_rejection_threshold: 0.5                 # Reduced from 0.8
        imu0_twist_rejection_threshold: 0.5                # Reduced from 0.8
        imu0_linear_acceleration_rejection_threshold: 0.5  # Reduced from 0.8

        # Remove gravity from acceleration readings
        imu0_remove_gravitational_acceleration: true

        # Control input settings (for prediction phase)
        use_control: true
        stamped_control: false
        control_timeout: 0.2
        control_config: [true, false, false, false, false, true]  # vx and vyaw
        
        # Acceleration limits for control commands
        acceleration_limits: [1.3, 0.0, 0.0, 0.0, 0.0, 3.0]  # Reduced yaw acceleration limit
        deceleration_limits: [1.3, 0.0, 0.0, 0.0, 0.0, 3.0]  # Made symmetric with acceleration
        
        # Acceleration gains for control commands
        acceleration_gains: [0.8, 0.0, 0.0, 0.0, 0.0, 0.7]  # Reduced yaw gain for smoother response
        deceleration_gains: [1.0, 0.0, 0.0, 0.0, 0.0, 0.7]  # Matched to acceleration gain
        
        # Process noise covariance matrix - Adjusted for better fusion of odometry and IMU
        # Increased uncertainty for yaw to give more weight to IMU measurements
        # Decreased uncertainty for position to trust odometry more
        process_noise_covariance: [0.03,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.03,   0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.06,   0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     
                                   0.0,    0.0,    0.0,    0.03,   0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.03,   0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.08,   0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.03,    0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.03,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.04,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.01,   0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.01,   0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.015,  0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.01,   0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.01,   0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.015]
                                   
        # Initial estimate covariance - Keep defaults for rapid convergence
        initial_estimate_covariance: [1e-9,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    1e-9,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    1e-9,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    1e-9,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,    0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     1e-9,    0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     1e-9,    0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     1e-9,   0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    1e-9,   0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    1e-9]
