# *****************************************************************************************
# *
# *        =============================================
# *                  LB Theme (eYRC 2024-25)
# *        =============================================
# *
# *
# *  Filename:        ukf.yaml
# *  Description:     UKF configuration for 2D robot localization with odometry and IMU.
# *  Created:         23/02/2025
# *  Modified by:     Team 1654
# *  
# *****************************************************************************************

ukf_filter_node:
    ros__parameters:
        # Core Settings
        frequency: 30.0
        sensor_timeout: 0.1
        two_d_mode: true         # Restrict to 2D plane
        transform_time_offset: 0.0
        transform_timeout: 0.0
        print_diagnostics: true  # Monitor diagnostics_agg for issues
        publish_tf: true         # Broadcast odom→base_link transform

        # Frame Configuration
        map_frame: map
        odom_frame: odom
        base_link_frame: ebot_base_link  # Must match your robot's base link
        world_frame: odom                # Fuse data in the odom frame

        # Odometry Input (Wheel Encoders)
        odom0: /odom                     # Topic for wheel odometry
        odom0_config: [true,  true,  false,   # x, y (enable), z (disable)
                      false, false, false,   # roll, pitch, yaw (disabled - IMU handles orientation)
                      true,  true,  false,    # vx, vy (enable), vz (disable)
                      false, false, true,     # vroll, vpitch, vyaw (enable vyaw for angular velocity)
                      false, false, false]    # ax, ay, az (disable acceleration)
        odom0_queue_size: 10
        odom0_differential: false
        odom0_relative: false
        odom0_pose_rejection_threshold: 5.0   # Relaxed threshold for odometry jumps
        odom0_twist_rejection_threshold: 1.0  # Strict velocity outlier rejection

        # IMU Input
        imu0: /sensors/imu1                  # IMU topic (REP-103 compliant, ENU frame)
        imu0_config: [false, false, false,   # x, y, z position (disable)
                     true,  true,  true,     # roll, pitch, yaw (enable orientation)
                     false, false, false,    # vx, vy, vz (disable)
                     false, false, true,     # vroll, vpitch, vyaw (enable vyaw)
                     true,  true,  false]    # ax, ay (enable linear acceleration), az (disable)
        imu0_differential: false
        imu0_relative: true                  # Treat IMU data as relative to initial orientation
        imu0_queue_size: 10
        imu0_remove_gravitational_acceleration: true  # Critical for linear acceleration
        imu0_pose_rejection_threshold: 0.8   # Strict orientation outlier rejection
        imu0_twist_rejection_threshold: 0.5  # Angular velocity rejection
        imu0_linear_acceleration_rejection_threshold: 0.5  # Linear acceleration rejection

        # Control Input (Optional - Enable if using cmd_vel)
        use_control: true  # Enable control input for prediction
        stamped_control: false  # Set to true if using TwistStamped messages
        control_timeout: 0.2  # Timeout for control commands (seconds)
        control_config: [true, false, false, false, false, true]  # Use vx and vyaw from cmd_vel        

        # UKF Sigma Point Parameters
        alpha: 0.1   # Spread of sigma points (0.001 < alpha < 1)
        kappa: 3.0   # Secondary scaling parameter (0 for default)
        beta: 2.0    # Prior knowledge (2.0 for Gaussian distributions)

        # Process Noise Covariance (Tuned for 2D differential drive)
        process_noise_covariance: [
            0.05,   0.0,    0.0,    0.0,    0.0,    0.1,    # x, y, z, roll, pitch, yaw
            0.0,    0.05,   0.0,    0.0,    0.0,    0.0,    # vx, vy, vz, vroll, vpitch, vyaw
            0.0,    0.0,    0.06,   0.0,    0.0,    0.0,    # ax, ay, az
            0.0,    0.0,    0.0,    0.03,   0.0,    0.0,
            0.0,    0.0,    0.0,    0.0,    0.03,   0.0,
            0.0,    0.0,    0.0,    0.0,    0.0,    0.06,
            0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
            0.025,  0.0,    0.0,    0.0,    0.0,    0.0,
            0.0,    0.025,  0.0,    0.0,    0.0,    0.0,
            0.0,    0.0,    0.04,   0.0,    0.0,    0.0,
            0.0,    0.0,    0.0,    0.01,   0.0,    0.0,
            0.0,    0.0,    0.0,    0.0,    0.01,   0.0,
            0.0,    0.0,    0.0,    0.0,    0.0,    0.02,
            0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
            0.01,   0.0,    0.0,    0.0,    0.0,    0.0,
            0.0,    0.01,   0.0,    0.0,    0.0,    0.0,
            0.0,    0.0,    0.015
        ]

        # Initial State Covariance (Small values for quick convergence)
        initial_estimate_covariance: [
            1e-9, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    1e-9, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9
        ]